micronaut:
  application:
    name: pcc-puppet-enforcer-realm
  server:
    port: 9900
    netty:
      access-logger:
        enabled: false
        loggerName: HTTP_ACCESS_LOGGER
        log-format: "%h %r %s %b %D %{User-Agent}i %{Version}o %{uber-trace-id}o"
        exclusions:
          - /health.*
  metrics:
    enabled: true
    binders:
      jvm:
        enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    token:
      enabled: true
      propagation:
        enabled: true
        service-id-regex: pcc-realm.*
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: ${jwks-uri}
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
    authentication: bearer
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: ${provider-keycloak-url}
            configuration-path: /realms/${keycloak-realm}/.well-known/openid-configuration
            authorization:
              max-age: 300
          grant-type: password
          client-id: ${keycloak-clientId}
          client-secret: ${keycloak-clientSecret}
          authorization:
            url: ${provider-keycloak-url}/realms/${keycloak-realm}/protocol/openid-connect/auth
          token:
            url: ${provider-keycloak-url}/realms/${keycloak-realm}/protocol/openid-connect/token
            auth-method: client_secret_post
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    services:
      pcc-realm-organization:
        url: ${pcc-realm-organization-url}
        path: ${pcc-realm-organization-path}
      pcc-realm-department:
        url: ${pcc-realm-department-url}
        path: ${pcc-realm-department-path}
      pcc-realm-member:
        url: ${pcc-realm-member-url}
        path: ${pcc-realm-member-path}
      pcc-realm-passport:
        url: ${pcc-realm-passport-url}
        path: ${pcc-realm-passport-path}
      provider-rest-countries:
        url: ${provider-rest-countries-url}
        path: ${provider-rest-countries-path}
      provider-keycloak:
        url: ${provider-keycloak-url}
      provider-vault:
        url: ${HC_VAULT_URI}
  caches:
    keycloak:
      maximum-size: 10
      expire-after-write: PT4M
    organization:
      maximum-size: 50
      expire-after-write: PT15M
    department:
      maximum-size: 50
      expire-after-write: PT15M
    member:
      maximum-size: 50
      expire-after-write: PT15M

endpoints:
  info:
    enabled: true
    sensitive: true
  beans:
    enabled: true
    sensitive: true
  loggers:
    enabled: true
    sensitive: true
    write-sensitive: true
  refresh:
    enabled: true
    sensitive: true
  routes:
    enabled: true
    sensitive: true
  env:
    enabled: true
    sensitive: true
  stop:
    enabled: true
    sensitive: true

netty:
  default:
    allocator:
      max-order: 3

worker:
  queue-type: local
  enabled: true

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      url: ${jdbc-uri}
      username: ${jdbc-username}
      password: ${jdbc-password}
      baseline-on-migrate: true
      baseline-version: 0
      locations:
        - classpath:migration

datasources:
  default:
    pooled: true
    jmxExport: true
    dbCreate: none
    url: ${jdbc-uri}
    dialect: ${jdbc-dialect}
    username: ${jdbc-username}
    password: ${jdbc-password}

r2dbc:
  datasources:
    default:
      url: ${r2dbc-uri}
      dialect: ${jdbc-dialect}
      username: ${jdbc-username}
      password: ${jdbc-password}
      options:
        driver: pool
        protocol: postgresql
        poolName: ${micronaut.application.name}-pool
        minIdle: 0
        maxSize: 10
        initialSize: 5

provider:
  keycloak:
    clientId: ${keycloak-clientId}
    clientSecret: ${keycloak-clientSecret}
    realm: ${keycloak-realm}
  vault:
    uri: ${HC_VAULT_URI}
    token: ${HC_VAULT_TOKEN}