micronaut:
  application:
    name: pcc-puppet-enforcer-realm
  server:
    port: 9900
    netty:
      access-logger:
        enabled: true
        loggerName: HTTP_ACCESS_LOGGER
        log-format: "%h %r %s %b %D %{User-Agent}i %{Version}o %{uber-trace-id}o"
        exclusions:
          - /health
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    enabled: true
    token:
      enabled: true
      propagation:
        enabled: true
        service-id-regex: \/realm\/.*
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: ${jwks-uri}
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    services:
      pcc-realm-organization:
        url: http://localhost:${micronaut.server.port}
        path: /realm/organization
      pcc-realm-department:
        url: http://localhost:${micronaut.server.port}
        path: /realm/department
      pcc-realm-member:
        url: http://localhost:${micronaut.server.port}
        path: /realm/member
      pcc-realm-passport:
        url: http://localhost:${micronaut.server.port}
        path: /realm/passport
      provider-rest-countries:
        url: ${provider-rest-countries-url}
      provider-keycloak:
        url: ${provider-keycloak-url}
  caches:
    keycloak:
      maximum-size: 10
      expire-after-write: PT4M

netty:
  default:
    allocator:
      max-order: 3

worker:
  queue-type: local
  enabled: true

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      url: ${jdbc-uri}
      username: ${jdbc-username}
      password: ${jdbc-password}
      baseline-on-migrate: true
      baseline-version: 0
      locations:
        - classpath:migration

datasources:
  default:
    pooled: true
    jmxExport: true
    dbCreate: none
    url: ${jdbc-uri}
    dialect: ${jdbc-dialect}
    username: ${jdbc-username}
    password: ${jdbc-password}

r2dbc:
  datasources:
    default:
      url: ${r2dbc-uri}
      dialect: ${jdbc-dialect}
      username: ${jdbc-username}
      password: ${jdbc-password}


provider:
  keycloak:
    clientId: ${keycloak-clientId}
    clientSecret: ${keycloak-clientSecret}
    realm: ${keycloak-realm}
