server:
  port: 9900
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 5KB

spring:
  application:
    name: pcc-puppet-enforcer-realm
  main:
    web-application-type: reactive

  cloud:
    vault:
      kv:
        application-name: ${spring.application.name},global
      config:
        lifecycle:
          enabled: true
          min-renewal: 30s

logging:
  pattern:
    console: "[${spring.application.name}] [%t] [%-5p] [%X{traceId}] [%X{spanId}] [%X{track-id}] [%logger{15}] [%m]%n"
  level:
    reactor.netty.http.client: INFO
    io.micrometer: INFO
    pcc: DEBUG