micronaut:
  application:
    name: pcc-puppet-enforcer-realm
  server:
    port: 9900
    netty:
      access-logger:
        enabled: true
        loggerName: HTTP_ACCESS_LOGGER
        log-format: "%h %r %s %b"
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  security:
    enabled: true
    token:
      enabled: true
      propagation:
        enabled: true
        service-id-regex: \/realm\/.*
      jwt:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: ${AUTH_JKWS:`http://desktop-egi38ur-docker-desktop-1:8080/auth/realms/master/.well-known/openid-configuration`}
    oauth2:
      clients:
        keycloak:
          openid:
            issuer: http://desktop-egi38ur-docker-desktop-1:8080/auth/realms/master
            jwks-uri: http://desktop-egi38ur-docker-desktop-1:8080/auth/realms/master/.well-known/openid-configuration
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    services:
      pcc-realm-organization:
        path: /realm/organization
      pcc-realm-department:
        path: /realm/department
      pcc-realm-member:
        path: /realm/member
      pcc-realm-passport:
        path: /realm/passport
      provider-rest-countries:
        url: https://restcountries.com/v3.1

otel:
  service:
    name: ${micronaut.application.name}
  traces:
    exporter: otlp,jaeger,logging
    propagator: tracecontext, baggage
  exclusions:
    - /health

netty:
  default:
    allocator:
      max-order: 3

worker:
  queue-type: local
  enabled: true

flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      url: 'jdbc:postgresql://localhost:5432/pcc_realm'
      username: postgres
      password: postgres
      baseline-on-migrate: true
      baseline-version: 0
      locations:
        - classpath:migration

datasources:
  default:
    pooled: true
    jmxExport: true
    dbCreate: none
    url: 'jdbc:postgresql://localhost:5432/pcc_realm'
    dialect: postgres
    username: postgres
    password: postgres

r2dbc:
  datasources:
    default:
      url: 'r2dbc:postgresql://localhost:5432/pcc_realm'
      dialect: postgres
      username: postgres
      password: postgres
