spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ${mongo-uri}

  security:
    oauth2:
      resourceserver:
        jwk:
          jwk-set-uri: ${provider-keycloak-url}/realms/${keycloak-realm}/.well-known/openid-configuration
          issuer-uri: ${provider-keycloak-url}/realms/${keycloak-realm}
        jwt:
          issuer: ${provider-keycloak-url}/realms/${keycloak-realm}
  http:
    services:
      pcc-realm-organization:
        url: ${pcc-realm-organization-url}
        path: ${pcc-realm-organization-path}
      pcc-realm-department:
        url: ${pcc-realm-department-url}
        path: ${pcc-realm-department-path}
      pcc-realm-member:
        url: ${pcc-realm-member-url}
        path: ${pcc-realm-member-path}
      pcc-realm-passport:
        url: ${pcc-realm-passport-url}
        path: ${pcc-realm-passport-path}
      provider-rest-countries:
        url: ${provider-rest-countries-url}
        path: ${provider-rest-countries-path}
      provider-keycloak:
        url: ${provider-keycloak-url}
      provider-vault:
        url: ${provider-vault-url}

  r2dbc:
    name: ${r2dbc-database}
    url: ${r2dbc-uri}
    username: ${jdbc-username}
    password: ${jdbc-password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

management:
  tracing:
    baggage:
      correlation:
        enabled: true
        fields:
          - track-id
      remote-fields:
        - track-id
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: ${zipkin-url}

provider:
  keycloak:
    adminClientId: ${keycloak-admin-clientId}
    clientId: ${keycloak-clientId}
    clientSecret: ${keycloak-clientSecret}
    realm: ${keycloak-realm}
  vault:
    uri: ${provider-vault-url}
    token: ${provider-vault-token}
