server:
  port: 9900
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 5KB

spring:
  application:
    name: pcc-puppet-enforcer-realm
  main:
    web-application-type: reactive

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://pcc:123456789@mbp.lan:27017/fuimos

  security:
    oauth2:
      resourceserver:
        jwk:
          jwk-set-uri: ${provider-keycloak-url}/realms/${keycloak-realm}/.well-known/openid-configuration
          issuer-uri: ${provider-keycloak-url}/realms/${keycloak-realm}
        jwt:
          issuer: ${provider-keycloak-url}/realms/${keycloak-realm}
  cloud:
    vault:
      kv:
        application-name: ${spring.application.name},global
      config:
        lifecycle:
          enabled: true
          min-renewal: 30s
  http:
    services:
      pcc-realm-organization:
        url: ${pcc-realm-organization-url}
        path: ${pcc-realm-organization-path}
      pcc-realm-department:
        url: ${pcc-realm-department-url}
        path: ${pcc-realm-department-path}
      pcc-realm-member:
        url: ${pcc-realm-member-url}
        path: ${pcc-realm-member-path}
      pcc-realm-passport:
        url: ${pcc-realm-passport-url}
        path: ${pcc-realm-passport-path}
      provider-rest-countries:
        url: ${provider-rest-countries-url}
        path: ${provider-rest-countries-path}
      provider-keycloak:
        url: ${provider-keycloak-url}
      provider-vault:
        url: ${provider-vault-url}

  flyway:
    url: ${jdbc-uri}
    user: ${jdbc-username}
    password: ${jdbc-password}
    locations:
      - classpath:db/migration

  r2dbc:
    name: pcc_realm
    url: ${r2dbc-uri}
    dialect: ${jdbc-dialect}
    username: ${jdbc-username}
    password: ${jdbc-password}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50

datasources:
  default:
    pooled: true
    jmxExport: true
    dbCreate: none
    url: ${jdbc-uri}
    dialect: ${jdbc-dialect}
    username: ${jdbc-username}
    password: ${jdbc-password}


management:
  tracing:
    baggage:
      correlation:
        enabled: true
        fields:
          - track-id
      remote-fields:
        - track-id
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://mbp.lan:9411/api/v2/spans

provider:
  keycloak:
    adminClientId: admin-cli
    clientId: ${keycloak-clientId}
    clientSecret: ${keycloak-clientSecret}
    realm: ${keycloak-realm}
  vault:
    uri: ${provider-vault-url}
    token: ${provider-vault-token}


logging:
  pattern:
    console: "[${spring.application.name}] [%t] [%-5p] [%X{traceId}] [%X{spanId}] [%X{track-id}] [%logger{15}] [%m]%n"
  level:
    io.micrometer: INFO
    pcc: DEBUG