CREATE TABLE MEMBER
(
    ID         VARCHAR(32) NOT NULL PRIMARY KEY,
    ORGANIZATION_ID  VARCHAR(32) NOT NULL,
    DEPARTMENT_ID  VARCHAR(32) NOT NULL,
    USERNAME       VARCHAR(64) NOT NULL,
    PASSWORD       VARCHAR(64) NOT NULL,
    CONTACT_ID VARCHAR(32) NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(64),
    UPDATED_AT TIMESTAMP,
    VERSION    INT,
    CONSTRAINT FK_MEMBER_CONTACT FOREIGN KEY (CONTACT_ID)
        REFERENCES CONTACT_INFORMATION (ID),
    CONSTRAINT FK_MEMBER_PARENT_ORGANIZATION_ID FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES ORGANIZATION (ID),
    CONSTRAINT FK_MEMBER_PARENT_DEPARTMENT_ID FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (ID)
);
