apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcc-puppet-enforcer-realm-deployment
  namespace: pcc-puppet-enforcer
  labels:
    app: pcc-puppet-enforcer-realm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcc-puppet-enforcer-realm-deployment
  template:
    metadata:
      name: pcc-puppet-enforcer-realm-deployment
      labels:
        app: pcc-puppet-enforcer-realm-deployment
      annotations:
        linkerd.io/inject: enabled
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: pcc-registry
      containers:
        - name: pcc-puppet-enforcer-realm-container
          image: ghcr.io/pandinocloudcrew/pcc-puppet-enforcer-realm:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: SPRING_CLOUD_VAULT_AUTHENTICATION
              value: token
            - name: SPRING_CLOUD_VAULT_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_VAULT_KV_BACKEND
              value: k8s
            - name: SPRING_CLOUD_VAULT_PORT
              value: '443'
            - name: SPRING_CLOUD_VAULT_SCHEME
              value: https
            - name: SPRING_CONFIG_IMPORT
              value: vault://
            - name: SPRING_CLOUD_VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-config
                  key: HC_VAULT_URI
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-config
                  key: HC_VAULT_TOKEN
          ports:
            - name: http
              containerPort: 9900
          readinessProbe:
            tcpSocket:
              port: 9900
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 9900
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 10
            successThreshold: 1