apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pcc-puppet-enforcer-realm-ingress
  namespace: pcc-puppet-enforcer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`realm.pcc.local`)
      priority: 10
      services:
        - name: pcc-puppet-enforcer-realm-service
          port: 9900
  tls:
    certResolver: default