CREATE TABLE CONTACT_INFORMATION
(
    ID           VARCHAR(32) NOT NULL PRIMARY KEY,
    OWNER_ID     VARCHAR(32) NOT NULL,
    FIRST_NAME   VARCHAR(32) NOT NULL,
    LAST_NAME    VARCHAR(32) NOT NULL,
    PHONE_NUMBER VARCHAR(32) NOT NULL,
    EMAIL        VARCHAR(64) NOT NULL,
    POSITION     VARCHAR(64) NOT NULL,
    ZONE_ID      VARCHAR(32) NOT NULL,
    LOCALE       VARCHAR(32) NOT NULL,
    COUNTRY      VARCHAR(64) NOT NULL,
    CITY         VARCHAR(64) NOT NULL,
    CURRENCY     VARCHAR(32) NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(64),
    UPDATED_AT TIMESTAMP,
    VERSION    INT
);

CREATE TABLE ORGANIZATION
(
    ID         VARCHAR(32) NOT NULL PRIMARY KEY,
    PARENT_ID  VARCHAR(32),
    NAME       VARCHAR(64) NOT NULL,
    LOCATION   VARCHAR(64) NOT NULL,
    COUNTRY    VARCHAR(64) NOT NULL,
    CITY       VARCHAR(64) NOT NULL,
    TAX_ID      VARCHAR(64) NOT NULL,
    CONTACT_ID VARCHAR(32) NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(64),
    UPDATED_AT TIMESTAMP,
    VERSION    INT,
    CONSTRAINT FK_ORGANIZATION_CONTACT FOREIGN KEY (CONTACT_ID)
        REFERENCES CONTACT_INFORMATION (ID)
);
