CREATE TABLE DEPARTMENT
(
    ID         VARCHAR(32) NOT NULL PRIMARY KEY,
    PARENT_ID  VARCHAR(32),
    ORGANIZATION_ID  VARCHAR(32) NOT NULL,
    NAME       VARCHAR(64) NOT NULL,
    LOCATION   VARCHAR(64) NOT NULL,
    CONTACT_ID VARCHAR(32) NOT NULL,
    CREATED_BY VARCHAR(64) NOT NULL,
    CREATED_AT TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(64),
    UPDATED_AT TIMESTAMP,
    VERSION    INT,
    CONSTRAINT FK_DEPARTMENT_CONTACT FOREIGN KEY (CONTACT_ID)
        REFERENCES CONTACT_INFORMATION (ID),
    CONSTRAINT FK_DEPARTMENT_PARENT_ORGANIZATION_ID FOREIGN KEY (ORGANIZATION_ID)
        REFERENCES ORGANIZATION (ID)
);
