name: GraalVM CE CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: 22.2.0.java17
      - name: Ignore Gradlew changes
        run: git update-index --assume-unchanged gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Install Native Image
        run: gu install native-image
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.GH_PAT_USERNAME }}
          password: ${{ secrets.GH_PAT }}
      - name: Build And Push Docker Image
        env:
          DOCKER_REPOSITORY_PATH: ${{ secrets.DOCKER_REPOSITORY_PATH }}
          DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          export DOCKER_IMAGE=`echo "${DOCKER_REGISTRY_URL}/${DOCKER_REPOSITORY_PATH}/pcc-puppet-enforcer-realm-native" | sed -e 's#//#/#' -e 's#^/##'`
          ./gradlew check dockerPushNative --no-daemon
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.36.1
      - uses: actions/checkout@master
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: deploy to cluster
        run: |
          kubectl set image deployment/pcc-puppet-enforcer-realm-deployment pcc-puppet-enforcer-realm-container=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.DOCKER_REPOSITORY_PATH }}/pcc-puppet-enforcer-realm-native:${{ github.ref_name }}
      - name: verify deployment
        run: |
          kubectl rollout status deployment/pcc-puppet-enforcer-realm-deployment