name: Push to Registry using GraalVM CE CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.m2/repository
          key: ${{ runner.os }}-gradle-test-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-test-
      - name: Setup GraalVM CE
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: 22.2.0.java17
      - name: Ignore Gradlew changes
        run: git update-index --assume-unchanged gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Install Native Image
        run: gu install native-image
      - name: lowercase repository name
        env:
          DOCKER_IMAGE_UPPERCASE: ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}
        run: |
          echo "DOCKER_IMAGE=${DOCKER_IMAGE_UPPERCASE,,}" >>${GITHUB_ENV}
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Native And Push Docker Image
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
        run: |
          ./gradlew check dockerPushNative --no-daemon
